export enum LoginErrorTypes {
    LOGIN_UNAUTHORIZED,
    LOGIN_FORBIDDEN,
    LOGIN_NOT_FOUND,
    LOGIN_UNKNOWN,
    LOGIN_SESSION_NOT_FOUND,
    LOGIN_SESSION_UNKNOWN,

    PROFILE_IMAGE_NOT_FOUND,
    PROFILE_IMAGE_UNKNOWN,
}